interval_secs = 30
discord_webhook_url = "https://discord.com/api/webhooks/1498514698411311106/JJr7FNMcxaG0KfDAoEW3Inew2RIUcd9e5E6cAo3nblD09ckg0WQM6snN9MZRlspA4NTU"

[[services]]
name = "Auth Service"
url = "http://thisis-fake-url.co.th"
method = "HTTP"
restart_command = "systemctl restart auth-service"
recovery_delay = 30
