interval_secs = 30
discord_webhook_url = "https://discord.com/api/webhooks/1498514698411311106/JJr7FNMcxaG0KfDAoEW3Inew2RIUcd9e5E6cAo3nblD09ckg0WQM6snN9MZRlspA4NTU"

[[services]]
name = "Auth Service"
url = "http://192.168.1.10:8080/health"
method = "HTTP"
restart_command = "systemctl restart auth-service"

[[services]]
name = "VPN Gateway"
url = "192.168.1.1:1194"
method = "TCP"
restart_command = "systemctl restart openvpn@server"

[[services]]
name = "PostgreSQL"
url = "192.168.1.20:5432"
method = "TCP"
restart_command = "systemctl restart postgresql"

[[services]]
name = "Nginx Proxy"
url = "http://192.168.1.5/healthz"
method = "HTTP"
restart_command = "systemctl reload nginx"
